### ISSUE TITLE
i tried to replace "cv2.VideoCapture" to"cv2.imread" .. are it possible in facenet real time 

### ISSUE THREAD

**Issue by DinaIbrahim132** [serengil/tensorflow-101#14]

**Comment by serengil** [comment]
Facenet real time code is here: https://github.com/serengil/tensorflow-101/blob/master/python/facenet-real-time.py

Why you replace videocapture to imread? If you want to read stream data from video instead of webcam, you just pass the location.

cap = cv2.VideoCapture('video.mp4') #process videos
cap = cv2.VideoCapture(0) #process real time web-cam
